apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 9Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/raw"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kbench-local-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kbench-local
spec:
  template:
    metadata:
      labels:
        kbench: fio-local
    spec:
      containers:
        - name: kbench
          image: yasker/kbench:latest
          imagePullPolicy: Always
          env:
            #- name: QUICK_MODE  # for debugging
            #  value: "1"
            - name: FILE_NAME
              value: "/volume/test"
            - name: SIZE
              value: "2G" # must be 10% smaller than the PVC size due to filesystem also took space
          volumeMounts:
            - name: vol
              mountPath: /volume/
          #volumeDevices:
          #- name: vol
          #  devicePath: /volume/test
      restartPolicy: Never
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: kbench-local-pvc
  backoffLimit: 0
