apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kbench-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kbench
spec:
  template:
    metadata:
      labels:
        kbench: fio
    spec:
      containers:
        - name: kbench
          image: yasker/kbench:latest
          imagePullPolicy: Always
          env:
            #- name: QUICK_MODE  # for debugging
            #  value: "1"
            - name: FILE_NAME
              value: "/volume/test"
            - name: SIZE
              value: "2G" # must be 10% smaller than the PVC size due to filesystem also took space
          volumeMounts:
            - name: vol
              mountPath: /volume/
          #volumeDevices:
          #- name: vol
          #  devicePath: /volume/test
      restartPolicy: Never
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: kbench-pvc
  backoffLimit: 0
